In [1]:
import numpy as np

import sys
sys.path.append("..")
from src import color_schemes

In [2]:
z_min, z_max = 0.1,1
levels = np.linspace(z_min,z_max,10)#[1:6]
colormap_green = color_schemes.create_color_brewer_colorscheme("green",levels)

In [3]:
colormap_green

[array([1., 1., 1., 1.]),
 array([0.85098039, 0.94196078, 0.82823529, 1.        ]),
 array([0.74980392, 0.90196078, 0.72235294, 1.        ]),
 array([0.65098039, 0.85960784, 0.62666667, 1.        ]),
 array([0.45490196, 0.76862745, 0.4627451 , 1.        ]),
 array([0.24235294, 0.66431373, 0.35764706, 1.        ]),
 array([0.17019608, 0.60156863, 0.30588235, 1.        ]),
 array([0.05490196, 0.4745098 , 0.21176471, 1.        ]),
 array([0.        , 0.36784314, 0.19137255, 1.        ]),
 array([0.        , 0.26666667, 0.10588235, 1.        ])]

In [4]:
z_min, z_max = 0.1, 1
levels = np.linspace(z_min,z_max,10)#[1:6]
colormap_green = color_schemes.create_color_brewer_colorscheme("green",levels,0)
colormap_green

[array([0.92313725, 0.97019608, 0.90666667, 1.        ]),
 array([0.85098039, 0.94196078, 0.82823529, 1.        ]),
 array([0.74980392, 0.90196078, 0.72235294, 1.        ]),
 array([0.65098039, 0.85960784, 0.62666667, 1.        ]),
 array([0.45490196, 0.76862745, 0.4627451 , 1.        ]),
 array([0.24235294, 0.66431373, 0.35764706, 1.        ]),
 array([0.17019608, 0.60156863, 0.30588235, 1.        ]),
 array([0.05490196, 0.4745098 , 0.21176471, 1.        ]),
 array([0.        , 0.36784314, 0.19137255, 1.        ]),
 array([0.        , 0.26666667, 0.10588235, 1.        ])]